filebeat.inputs:
- type: filestream
  enabled: false
  paths:
    - /var/log/*.log

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
  index.number_of_shards: 1
  
output.elasticsearch:
  hosts: ["172.31.9.62:9200"]
  index: "USERNAME-%{[agent.version]}-%{+yyyy.MM.dd}"

setup.template.enabled: true
setup.ilm.enabled: false
setup.template.name: "USERNAME-%{[agent.version]}"
setup.template.pattern: "USERNAME-%{[agent.version]}-*"

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~

