metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression

output.elasticsearch:
  hosts: ["172.31.9.62:9200"]
  index: "mb-USERNAME-%{[agent.version]}-%{+yyyy.MM.dd}"

setup.template.enabled: true
setup.ilm.enabled: false
setup.template.name: "mb-USERNAME-%{[agent.version]}"
setup.template.pattern: "mb-USERNAME-%{[agent.version]}-*"

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
